// Real line-item data extracted from Proposal #497 (Lauren Brant residence).
window.proposalData = {
  proposalNumber: 497,
  title: 'Home Management, Network/WiFi & Audio Visual',
  client: {
    name: 'Lauren Brant',
    email: 'laurenlbrant@gmail.com',
    phone: '(415) 215-7665',
    addressLine1: '61469 Hackleman Court',
    addressLine2: 'Bend, OR 97702',
  },
  company: {
    name: 'SecuraCore',
    url: 'https://www.mysecuracore.com',
    phone: '(503) 704-8409',
    addressLine1: '404 NE Norton Ave.',
    addressLine2: 'Bend, OR 97701',
    ccb: '230919',
  },
  preparer: 'Matt Schaberg',
  expires: 'December 08, 2025',
  scope: 'Provide and install a Qolsys smart home management panel with door/window sensors, garage door controls, smart locks, and integrated Z-Wave lighting controls. Add Alarm.com outdoor surveillance cameras and a video doorbell. Install Sonos Amp for distributed audio across living room and exterior deck speakers. All components integrated into the Alarm.com app for unified control.',
  floorplan: 'Brant Residence - 61469 Hackleman.pdf',
  clarifications: [
    'SecuraCore will program all devices into the Alarm.com ecosystem',
    'Homeowner-supplied MyQ garage hub to be reset and reprogrammed',
    'Electrical work at the exterior sconce locations to be provided by others',
  ],
  areas: [
    {
      name: 'Home Management / Property Awareness',
      lines: [
        { brand: 'Qolsys',       kind: 'item',  desc: 'Smart Home Management Panel — Easily integrate with Alexa, Security, Locks, Thermostats, Lights, Garage Doors, Cameras and More.', location: '', price: 799.99, qty: 1, total: 799.99 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 1, total: 149.00 },
        { brand: 'DSC',          kind: 'item',  desc: 'Wireless PowerG Door and Window Contact — monitors doors and windows for activity', location: 'Front Door, Interior Garage, Hallway Slider, Living Room', price: 99.99, qty: 4, total: 399.96 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 2, total: 298.00 },
        { brand: 'Chamberlain',  kind: 'item',  desc: 'MyQ Smart Garage Hub — open and close your garage door from anywhere. Receive left-open notifications and create daily schedules.', location: 'Main Garage — homeowner supplied', price: 0.00, qty: 1, total: 0.00 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor — Reset existing MyQ devices and program into Alarm.com', price: 149.00, qty: 0.5, total: 74.50 },
        { brand: 'Chamberlain',  kind: 'item',  desc: 'MyQ Smart Garage Hub', location: 'Side Garage', price: 199.99, qty: 1, total: 199.99 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 0.5, total: 74.50 },
        { brand: 'Yale',         kind: 'item',  desc: 'Black Suede Keypad Deadbolt Smart Lock', location: 'Garage Interior Door', price: 249.99, qty: 1, total: 249.99 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 1, total: 149.00 },
        { brand: 'Jasco',        kind: 'item',  desc: 'Z-Wave Plus In-Wall On/Off Smart Switch with QuickFit, SimpleWire', location: 'Driveway Sconces, Exterior Entry, Chandelier', price: 199.99, qty: 3, total: 599.97 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 1.5, total: 223.50 },
        { brand: 'Qolsys',       kind: 'item',  desc: 'Wireless Smoke and Heat Detector, PowerG Technology', location: 'Upstairs, Downstairs', price: 159.00, qty: 2, total: 318.00 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 1, total: 149.00 },
        { brand: 'Alarm.com',    kind: 'item',  desc: '1080p Outdoor Wi-Fi Camera with Two-Way Audio', location: 'Driveway, Patio', price: 329.99, qty: 2, total: 659.98 },
        { brand: 'Western Digital', kind: 'item', desc: '256GB Purple Surveillance SD Card', location: '', price: 79.99, qty: 2, total: 159.98 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 2, total: 298.00 },
        { brand: 'Alarm.com',    kind: 'item',  desc: 'Video Doorbell — Full HD Wired Video Doorbell Camera', location: 'Front Door', price: 329.99, qty: 1, total: 329.99 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 1, total: 149.00 },
      ],
      total: 5282.35,
    },
    {
      name: 'Audio Visual',
      lines: [
        { brand: 'Sonos',        kind: 'item',  desc: 'Sonos Amp — 125W per channel, brings Sonos streaming to any passive speakers indoors or outdoors. Powers bookshelf, tower, in-ceiling, or outdoor speakers.', location: 'AV Rack', price: 799.99, qty: 1, total: 799.99 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 2, total: 298.00 },
        { brand: 'Sonance',      kind: 'item',  desc: 'Visual Performance 6.5" In-Ceiling Speaker (Pair)', location: 'Living Room', price: 599.99, qty: 1, total: 599.99 },
        { brand: 'Pre-Wire',     kind: 'item',  desc: '16Awg/4C Speaker Cabling, Basic Wall Plates, and Connectors from AV Rack to (2) Speakers', location: 'Living Room', price: 200.00, qty: 1, total: 200.00 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 2, total: 298.00 },
        { brand: 'Sonance',      kind: 'item',  desc: 'Mariner Outdoor 6.5" Speaker (Pair)', location: 'Deck', price: 449.99, qty: 1, total: 449.99 },
        { brand: 'Pre-Wire',     kind: 'item',  desc: '16Awg/4C Speaker Cabling from AV Rack to exterior (2) Speakers', location: 'Deck', price: 200.00, qty: 1, total: 200.00 },
        { brand: 'Labor',        kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 2, total: 298.00 },
      ],
      total: 3143.97,
    },
  ],
  totals: {
    parts:    6645.32,
    labor:    1781.00,
    subtotal: 8426.32,
    total:    8426.32,
    taxExempt: true,
  },
  payments: [
    { label: 'Payment 1', terms: '50% of Proposal Total • Due Upon Proposal Acceptance', amount: 4213.16 },
    { label: 'Payment 2', terms: 'Outstanding Proposal Balance • Due Upon Job Completion', amount: 4213.16 },
  ],
};
