// Test proposal — Cascade Law Office, a commercial fit-out.
// Different shape from #497 to exercise the template: larger labor mix,
// more areas, higher overall total, more clarifications.
window.proposalData = {
  proposalNumber: 612,
  title: 'Cascade Law — Office Security, Network & AV Fit-Out',
  client: {
    name: 'Cascade Law LLP',
    email: 'ops@cascadelaw.com',
    phone: '(541) 317-0440',
    addressLine1: '1105 NW Wall Street, Suite 300',
    addressLine2: 'Bend, OR 97703',
  },
  company: {
    name: 'SecuraCore',
    url: 'https://www.mysecuracore.com',
    phone: '(503) 704-8409',
    addressLine1: '404 NE Norton Ave.',
    addressLine2: 'Bend, OR 97701',
    ccb: '230919',
  },
  preparer: 'Matt Schaberg',
  expires: 'June 15, 2026',
  scope: 'Complete low-voltage fit-out for a 6,200 sq ft law office on two floors. Scope includes: (1) Alarm.com commercial intrusion + access control with keypad entry at three exterior doors; (2) 8-camera surveillance system covering lobby, corridors, file room, and parking; (3) eero Pro mesh network with 4 access points and a 24-port PoE switch; (4) Sonos distributed audio for lobby and conference rooms; (5) Samsung displays with Logitech conference cameras in two conference rooms. All systems integrated into a single touch panel at reception.',
  floorplan: 'CascadeLaw_Suite300_FloorPlans_v4.pdf',
  clarifications: [
    'Power drops to server closet and camera heads to be provided by licensed electrician (by others).',
    'Ceiling access for AP and speaker installs coordinated with building GC.',
    'Monitoring service billed separately at $49.99/month per standard SecuraCore SMA.',
    'Conference room displays and mounts included; network switches to be rack-mounted in IDF closet.',
  ],
  areas: [
    {
      name: 'Reception / Lobby',
      lines: [
        { brand: 'Qolsys',      kind: 'item',  desc: 'IQ Panel 4 — 7" touchscreen commercial alarm + automation panel', location: 'Reception desk', price: 799.99, qty: 1, total: 799.99 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore Installation Labor — mount, wire, program to Alarm.com', price: 149.00, qty: 2, total: 298.00 },
        { brand: 'Alarm.com',   kind: 'item',  desc: 'ADC-VC727P 8MP Varifocal Bullet Camera with 2-way audio', location: 'Lobby entrance', price: 399.99, qty: 2, total: 799.98 },
        { brand: 'Pre-Wire',    kind: 'item',  desc: 'Cat6 cable run, wall plate, connectors — per camera', location: 'Lobby entrance', price: 150.00, qty: 2, total: 300.00 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 3, total: 447.00 },
        { brand: 'Sonos',       kind: 'item',  desc: 'Sonos Amp — 125W/ch streaming amplifier for in-ceiling speakers', location: 'Reception AV cubby', price: 799.99, qty: 1, total: 799.99 },
        { brand: 'Sonance',     kind: 'item',  desc: 'Visual Performance 6.5" In-Ceiling Speaker (Pair)', location: 'Lobby', price: 599.99, qty: 1, total: 599.99 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 3, total: 447.00 },
      ],
      total: 4491.95,
    },
    {
      name: 'Conference Rooms (2)',
      lines: [
        { brand: 'Samsung',     kind: 'item',  desc: '75" QN85C Neo QLED 4K Smart Display', location: 'Conference A & B', price: 1899.99, qty: 2, total: 3799.98 },
        { brand: 'Sanus',       kind: 'item',  desc: 'VLT7 Tilting Wall Mount, 42–90"', location: 'Conference A & B', price: 349.99, qty: 2, total: 699.98 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore Installation Labor — display mounting and cable management', price: 149.00, qty: 4, total: 596.00 },
        { brand: 'Sonance',     kind: 'item',  desc: 'VP66R In-Ceiling Speaker (Pair)', location: 'Conference A & B', price: 599.99, qty: 2, total: 1199.98 },
        { brand: 'Pre-Wire',    kind: 'item',  desc: '16Awg/4C Speaker Cabling + Cat6 HDMI baluns', location: 'Conference A & B', price: 250.00, qty: 2, total: 500.00 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore Installation Labor', price: 149.00, qty: 4, total: 596.00 },
        { brand: 'Logitech',    kind: 'item',  desc: 'Rally Bar Mini — all-in-one video conferencing camera and sound bar', location: 'Conference A & B', price: 1999.00, qty: 2, total: 3998.00 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore System Programming — calibrate cameras, test with Zoom / Teams', price: 159.00, qty: 3, total: 477.00 },
      ],
      total: 11866.94,
    },
    {
      name: 'Access Control & Surveillance',
      lines: [
        { brand: 'Alarm.com',   kind: 'item',  desc: 'ADC-VC727P 8MP Bullet Camera with 2-way audio', location: 'Rear entrance, parking (3), corridor (2)', price: 399.99, qty: 6, total: 2399.94 },
        { brand: 'Pre-Wire',    kind: 'item',  desc: 'Cat6 run + wall plate per camera', location: 'Cameras (6)', price: 150.00, qty: 6, total: 900.00 },
        { brand: 'Alarm.com',   kind: 'item',  desc: '16-Channel 12TB Commercial Stream Video Recorder', location: 'IDF closet', price: 1399.99, qty: 1, total: 1399.99 },
        { brand: 'Alarm.com',   kind: 'item',  desc: 'Commercial Access Control Keypad + Reader', location: 'Front, rear, file-room doors', price: 449.99, qty: 3, total: 1349.97 },
        { brand: 'Yale',        kind: 'item',  desc: 'Assure Commercial Deadbolt — electronic, keypad + app', location: 'Rear + file-room doors', price: 379.99, qty: 2, total: 759.98 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore Installation Labor — cameras, NVR, access hardware', price: 149.00, qty: 16, total: 2384.00 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore System Programming — Alarm.com cloud, user groups, schedules', price: 159.00, qty: 6, total: 954.00 },
      ],
      total: 10147.88,
    },
    {
      name: 'Network & WiFi',
      lines: [
        { brand: 'eero',        kind: 'item',  desc: 'eero Pro 7 Tri-Band Wi-Fi 7 Mesh Router', location: 'IDF closet (primary)', price: 349.99, qty: 1, total: 349.99 },
        { brand: 'eero',        kind: 'item',  desc: 'eero Pro 7 Mesh Access Point', location: 'Floor 1 + Floor 2 (3 APs)', price: 299.99, qty: 3, total: 899.97 },
        { brand: 'Netgear',     kind: 'item',  desc: 'GS324TP — 24-Port Gigabit PoE+ Managed Switch', location: 'IDF closet', price: 649.99, qty: 1, total: 649.99 },
        { brand: 'CyberPower',  kind: 'item',  desc: 'OR1500LCDRT2U 1500VA Line-Interactive UPS', location: 'IDF closet', price: 379.99, qty: 1, total: 379.99 },
        { brand: 'Pre-Wire',    kind: 'item',  desc: 'Cat6 cable runs for APs and workstation drops (24)', location: 'Both floors', price: 175.00, qty: 24, total: 4200.00 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore Installation Labor — rack-and-stack, terminations, testing', price: 149.00, qty: 10, total: 1490.00 },
        { brand: 'Labor',       kind: 'labor', desc: 'SecuraCore System Programming — VLANs, guest network, QoS', price: 159.00, qty: 4, total: 636.00 },
      ],
      total: 8605.94,
    },
  ],
  totals: {
    parts:    27030.71,
    labor:    8325.00,
    subtotal: 35355.71,
    total:    35355.71,
    taxExempt: false,
  },
  payments: [
    { label: 'Payment 1', terms: '40% of Proposal Total • Due Upon Proposal Acceptance', amount: 14142.28 },
    { label: 'Payment 2', terms: '40% of Proposal Total • Due at Material Delivery to Site', amount: 14142.29 },
    { label: 'Payment 3', terms: 'Outstanding Balance • Due Upon Job Completion', amount: 7071.14 },
  ],
};
